### ISSUE TITLE
How to create the file ~/.Renviron

### ISSUE THREAD

**Issue by zzfmyway** [Rich1000/lookr#1]
Where to put the file? What's the file name? Could you specify more on this step?

**Comment by Rich1000** [comment]
Hey, great to know someone has tried to use this - sorry about the cryptic description! The file should be called `.Renviron` and it should be placed in the home directory which can be shortened to `~/` but on my computer actually looks like this `/Users/rich/`

Basically `~/.Renviron` means `/Users/rich/.Renviron`

Good luck!

**Comment by zzfmyway** [comment]
Thank you for the reply! Actually I found another way earlier today and it works well. 

Run this code in R and set parameters instead of creating a file. 
`
Sys.setenv(LOOKER_API_PATH = "https://???????.looker.com:19999/api/3.0", 
           LOOKER_CLIENT_ID = "???????", 
           LOOKER_CLIENT_SECRET = "?????")
`

I really like this package, especially in my case I couldn't install the official one LookR for some reason due to rJava issue. Thank you very much!
